from manim import *

class SienaIntro(Scene):
	def construct(self):
		sienacollege = Text("Siena College").set_color(GREEN_E).scale(2)
		triangle = Triangle().set_color(YELLOW_E).scale(1.50)
		square = Square().set_color(GREEN_E).scale(3)
		circle = Circle(fill_opacity=5).set_color(YELLOW_E).set_fill().scale(3)
		circle2 = Circle().set_color(GREEN_E).scale(3)
		physics = Text("Department of Physics and Astronomy").set_color(YELLOW_E)
		physics.next_to(sienacollege,DOWN,buff=0).scale(1)	
		self.play(Create(circle))
		self.play(Transform(circle, square))
		self.wait(.5)
		self.play(Transform(square, triangle))
		self.wait(.5)
		self.play(Transform(triangle, circle2))
		self.wait(.5)
		
		triangle_logo= triangle.scale(0.2)
		circle_logo= circle.scale(0.2)
		circle_logo.to_corner(DR)
		triangle_logo.to_corner(DR)
	#	self.play(FadeOut(circle))
	#	self.play(FadeOut(square))
		self.play(Transform(square, sienacollege))
		self.wait(.5)
		self.play(Write(physics))
		self.wait()
		self.play(FadeOut(physics))
		square.scale(0.15).next_to(circle,0,buff=0)
		self.wait()



		wordprob = Text("Equation Explainers").set_color(BLUE)
		self.play(Write(wordprob),run_time=4)
		self.wait()
		self.play(FadeOut(wordprob))
		self.wait()		
		prob1 = Text("If you want to know your position, after some time has\npassed, you take your starting position, add it to your\nstarting velocity multiplied by the time that has passed,\nthen add one-half the acceleration multiplied by the\ntime that has passed squared.").scale(.7)
		math1 = MathTex("X","(t)","=","X_{0}","+","V_{0}","t","+",".5","a","t^2").next_to(prob1,DOWN*3).scale(1.5)
		prob1[0:28].set_color(BLUE)
		prob1[28:51].set_color(YELLOW)
		prob1[51:79].set_color(RED)
		prob1[79:106].set_color(GREEN)
		prob1[106:139].set_color(PURPLE)
		prob1[139:154].set_color(ORANGE)
		prob1[154:169].set_color(PINK)
		prob1[169:210].set_color(BLUE)
		self.play(Write(prob1[0:28]))
		math1[0].set_color(BLUE)
		math1[1].set_color(YELLOW)
		math1[3].set_color(RED)
		math1[5].set_color(GREEN)
		math1[6].set_color(PURPLE)
		math1[8].set_color(ORANGE)
		math1[9].set_color(PINK)
		math1[10].set_color(BLUE)
		self.play(Write(math1[0])) 
		self.wait()
		self.play(Write(prob1[28:51]))
		self.play(Write(math1[1]))
		self.wait()
		self.play(Write(math1[2]))
		self.play(Write(prob1[51:79]))
		self.play(Write(math1[3]))
		self.wait()
		self.play(Write(math1[4]))
		self.play(Write(prob1[79:106]))
		self.play(Write(math1[5]))
		self.wait()
		self.play(Write(prob1[106:139]))
		self.play(Write(math1[6]))
		self.wait()
		self.play(Write(math1[7]))
		self.play(Write(prob1[139:154]))
		self.play(Write(math1[8]))
		self.wait()
		self.play(Write(prob1[154:169]))
		self.play(Write(math1[9]))
		self.wait()
		self.play(Write(prob1[169:210]))
		self.play(Write(math1[10]))
		self.wait()
		self.play(FadeOut(prob1))
		self.play(FadeOut(math1))
		self.wait(.5)

		prob2 = Text("An objects final velocity is equal to the velocity\nit started with plus its acceleration times the\namount of time that has passed.").scale(.7)
		math2 = MathTex("V_{f}", "=", "V_{i}", "+", "a","t").next_to(prob2, DOWN*3).scale(1.5)
		prob2[0:21].set_color(RED)
		prob2[30:54].set_color(YELLOW)
		prob2[58:74].set_color(GREEN)
		prob2[74:109].set_color(PURPLE)
		math2[0].set_color(RED)
		math2[2].set_color(YELLOW)
		math2[4].set_color(GREEN)
		math2[5].set_color(PURPLE)

		self.play(Write(prob2[0:21]))
		self.play(Write(math2[0]))
		self.wait()
		self.play(Write(prob2[21:30]))
		self.play(Write(math2[1]))
		self.play(Write(prob2[30:54]))
		self.play(Write(math2[2]))
		self.wait()
		self.play(Write(prob2[54:58]))
		self.play(Write(math2[3]))
		self.play(Write(prob2[58:74]))
		self.play(Write(math2[4]))
		self.wait()
		self.play(Write(prob2[74:109]))
		self.play(Write(math2[5]))
		self.wait()
	
		prob2.scale(.7).to_corner(UL)
		math2.scale(.7).to_corner(UL).shift(DOWN)
	
		note1 = Text("This is the same as...")
		self.play(Write(note1))
		self.wait()
		self.play(FadeOut(note1))
		self.wait()
		prob3 = Text("If you want to know your velocity after some time has passed,\nyou take your starting velocity and add your acceleration\ntimes the amount of time that has passed.").scale(.7)
		math3 = MathTex("V","(t)","=","V_{0}","+","a","t").next_to(prob3,DOWN*2).scale(1.5)
		prob3[0:27].set_color(BLUE)
		prob3[27:50].set_color(PINK)
		prob3[50:77].set_color(ORANGE)
		prob3[77:99].set_color(GREEN)
		prob3[99:145].set_color(RED)
		math3[0].set_color(BLUE)
		math3[1].set_color(PINK)
		math3[3].set_color(ORANGE)
		math3[5].set_color(GREEN)
		math3[6].set_color(RED)
		self.play(Write(prob3[0:27]))
		self.play(Write(math3[0]))
		self.wait()
		self.play(Write(prob3[27:50]))
		self.play(Write(math3[1]))
		self.wait()
		self.play(Write(math3[2]))
		self.play(Write(prob3[50:77]))
		self.play(Write(math3[3]))
		self.wait()
		self.play(Write(math3[4]))
		self.play(Write(prob3[77:99]))
		self.play(Write(math3[5]))
		self.wait()
		self.play(Write(prob3[99:145]))
		self.play(Write(math3[6]))
		self.wait()

		self.play(FadeOut(prob2))
		self.play(FadeOut(prob3))
		math2.scale(1.5).next_to(math3,UP)
		self.wait()

		note2 = Text("These two equations are identical, despite having\nslightly different descriptions and symbols. It's\nimportant to always think about what a symbol means\nbefore plugging in values!").scale(.7).next_to(math2,UP*2).set_color(BLUE)
		self.play(Write(note2),run_time=5)
		self.wait()
 
